spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fighteasy
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: MySuperSecretKey1234567890123456gkdfkgjfkdjgkdfjgdfkgfdkjgkfdjkgjkfdjgkdfjgk

server:
  port: 8080

logging:
  level:
    root: debug